/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-03 05:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.board.model.vo.Board;
import com.kh.member.model.vo.Member;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/include/header.jsp", Long.valueOf(1570015614601L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.board.model.vo.Board");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Board b = (Board)request.getAttribute("b");
	Board prev = (Board)request.getAttribute("prev");
	Board next = (Board)request.getAttribute("next");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .outer{\r\n");
      out.write("        width:900px;\r\n");
      out.write("        height:600px;\r\n");
      out.write("        background:lightpink;\r\n");
      out.write("        color:black;\r\n");
      out.write("        margin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    #inner{\r\n");
      out.write("        width:700px;\r\n");
      out.write("        height:600px;\r\n");
      out.write("        background:white;\r\n");
      out.write("        margin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:auto;\r\n");
      out.write("        overflow:auto;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #topArea{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        margin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:20px;\r\n");
      out.write("     \r\n");
      out.write("    }\r\n");
      out.write("    #headArea{\r\n");
      out.write("        width:150px;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        float:left;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #topBtn{\r\n");
      out.write("        width:200px;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        float:right;\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("    #topBtn div{\r\n");
      out.write("        display:inline-block;\r\n");
      out.write("        background:lightblue;\r\n");
      out.write("        width:60px;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    } \r\n");
      out.write("    #topBtn div:hover{\r\n");
      out.write("    \tcursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("    #content{\r\n");
      out.write("        width:698px;\r\n");
      out.write("        height:150px;\r\n");
      out.write("        border:1px solid black;\r\n");
      out.write("        overflow:auto;\r\n");
      out.write("    }\r\n");
      out.write("    #title{\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        width:500px;\r\n");
      out.write("        height:35px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("    }\r\n");
      out.write("    #nickname{\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    #bottomArea{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:35px;\r\n");
      out.write("        position:relative;\r\n");
      out.write("    }\r\n");
      out.write("    #img1{\r\n");
      out.write("        background:url(\"");
      out.print(request.getContextPath());
      out.write("/resources/img/eye.jpg\");\r\n");
      out.write("        background-size:cover;\r\n");
      out.write("        width:27px;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        float:right;\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        top:3px;\r\n");
      out.write("        right:130px;\r\n");
      out.write("    }\r\n");
      out.write("    #img2{\r\n");
      out.write("        background:url(\"");
      out.print(request.getContextPath());
      out.write("/resources/img/review.jpg\");\r\n");
      out.write("        background-size:cover;\r\n");
      out.write("        width:25px;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        float:right;\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        top:3px;\r\n");
      out.write("        right:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #img1_1{\r\n");
      out.write("        float:right;\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        top:3px;\r\n");
      out.write("        right:105px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #img2_1{\r\n");
      out.write("        float:right;\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        top:3px;\r\n");
      out.write("        right:25px;\r\n");
      out.write("    }\r\n");
      out.write("    #nextArea{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:45px;\r\n");
      out.write("        border:1px solid black;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath=request.getContextPath();
	Member mem=(Member)session.getAttribute("mem");
	String head=request.getParameter("head");
	if(head!=null){
		session.setAttribute("head", head);
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    div.aaa{\r\n");
      out.write("        width:100px;\r\n");
      out.write("        height:30px;\r\n");
      out.write("        border:0px solid;\r\n");
      out.write("        position:relative;\r\n");
      out.write("        float:left;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("    div.aaa div{\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        bottom:0px;\r\n");
      out.write("        width:0%;\r\n");
      out.write("        height:10%;\r\n");
      out.write("        opacity:0.7;\r\n");
      out.write("        background:white;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\r');
      out.write('\n');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<h1><a href=\"");
      out.print(contextPath );
      out.write("\">ITJobs</a></h1>\r\n");
      out.write("<hr>공통 \r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=main\">게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=free\">자유게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=study\">스터디</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=project\">프로젝트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=qna\">공지사항</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=form\">서식</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.qu\"><del>문의사항</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/notificationList.se\">공고검색(기업상세정보)</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/resumeList.se\">인재검색</a>\r\n");
      out.write("<hr>공통\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/views/login/join_law.jsp\">회원가입</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/login.me\">로그인</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a><br>\r\n");
      out.write("<hr>일반\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myApplyList.vo\">지원리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myCompanyList.like\"><del>관심기업</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotificationList.like\"><del>관심공고</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.re\">이력서 관리</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("+지원하기\r\n");
      out.write("<hr>기업\r\n");
      out.write("\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotification.me\">공고리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myResumeList.like\"><del>관심인재</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("<hr>관리자\n");
      out.write("\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/boardList.ad'\">게시판 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/replyList.ad'\">댓글 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/memberList.ad'\">회원 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/noticeList.ad'\">공고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.qu.ad'\">문의 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.de'\">신고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<br clear=\"both\">\r\n");
      out.write("<script>\r\n");
      out.write("    function lease(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("        aaa.eq(n).css({'background':'#ff4e0b','color':'white'})\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, 2000, 'linear', function(){\r\n");
      out.write("            aaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var aaa=$('.aaa')\r\n");
      out.write("\r\n");
      out.write("    aaa.on('mouseover',function(){\r\n");
      out.write("        aaa_div.eq(n).stop()\r\n");
      out.write("    }).on('mouseleave',function(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, (2000*(100-parseFloat(bar.css('width')))/100), 'linear', function(){\r\n");
      out.write("        \taaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    var n=0;\r\n");
      out.write("    var W=$('.aaa').css('width');\r\n");
      out.write("    var aaa_div=$('.aaa').children('div');\r\n");
      out.write("\r\n");
      out.write("    lease()\r\n");
      out.write("</script>\r\n");
      out.write("<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t <div class=\"outer\">\r\n");
      out.write("        <div id=\"inner\">\r\n");
      out.write("            <div id=\"topArea\">\r\n");
      out.write("                <div id=\"headArea\">");
      out.print( b.getHead() );
      out.write("</div>\r\n");
      out.write("                <div id=\"topBtn\">\r\n");
      out.write("                    <div onclick=\"deleteBtn()\">삭제</div>\r\n");
      out.write("                    <div>수정</div>\r\n");
      out.write("                    <div>신고</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"bottomArea\">\r\n");
      out.write("\t            <div id=\"title\">");
      out.print(b.getTitle() );
      out.write("</div>\r\n");
      out.write("\t            <div id=\"img1\"></div>\r\n");
      out.write("\t            <div id=\"img1_1\">");
      out.print(b.getCount() );
      out.write("</div>   \r\n");
      out.write("\t            <div id=\"img2\"></div>\r\n");
      out.write("\t            <div id=\"img2_1\">30</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"nickname\">");
      out.print(b.getNickname() );
      out.write("</div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"content\">");
      out.print(b.getContents() );
      out.write("</div>\r\n");
      out.write("        \r\n");
      out.write("        \t<br>\r\n");
      out.write("            <div id=\"nextArea\">\r\n");
      out.write("                <div>이전글 - ");
      out.print(prev.getTitle() );
      out.write(" </div>\r\n");
      out.write("                <div>다음글 - ");
      out.print(next.getTitle() );
      out.write(" </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<<script>\r\n");
      out.write("\t\tfunction deleteBtn(){\r\n");
      out.write("\t\t\tif(confirm(\"정말 삭제하시겠습니까?\") == true){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(contextPath);
      out.write("/delete.bo?bId=");
      out.print(b.getB_no());
      out.write("&head=");
      out.print(b.getHead());
      out.write("\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
