/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-09 22:45:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.board.model.vo.Board;
import com.kh.member.model.vo.Member;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/include/user/footer.jsp", Long.valueOf(1571194974606L));
    _jspx_dependants.put("/views/include/user/header_nav.jsp", Long.valueOf(1573125515900L));
    _jspx_dependants.put("/views/include/user/page_header.jsp", Long.valueOf(1570290686536L));
    _jspx_dependants.put("/views/include/user/js.jsp", Long.valueOf(1571194974610L));
    _jspx_dependants.put("/views/include/user/style.jsp", Long.valueOf(1570301765407L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.board.model.vo.Board");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   Board b = (Board)request.getAttribute("b");
   Board prev = (Board)request.getAttribute("prev");
   Board next = (Board)request.getAttribute("next");
   
   String[] videoName = new String[4];
   
   if(b .getVideo() != null){
    	videoName = b.getVideo().split("=");
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".max-small {\r\n");
      out.write("    width: auto; height: auto;\r\n");
      out.write("    max-width: 500px;\r\n");
      out.write("    max-height: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("<!-- import jobx -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/line-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.theme.default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/slicknav.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/colors/cyan.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/color-switcher.css\">");
      out.write("\r\n");
      out.write("<!-- End of import from jobx -->\r\n");
      out.write("\r\n");
      out.write("<!-- import of jobx -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery-min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/popper.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"resources/jobx/assets/js/color-switcher.js\"></script> -->\r\n");
      out.write("<script src=\"resources/jobx/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.slicknav.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/form-validator.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/contact-form-script.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/main.js\"></script>\r\n");
      out.write("<!-- <script src=\"resources/util/menubar_animation.js\"></script> -->");
      out.write("\r\n");
      out.write("<!-- End of import of jobx -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <header id=\"home\" class=\"hero-area\">\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath=request.getContextPath();
	Member mem=(Member)session.getAttribute("mem");
	String head=request.getParameter("head");
	/* String googleMem = (String)session.getAttribute("googleMem"); */

	if(head!=null){
		session.setAttribute("head", head);
}

      out.write('\r');
      out.write('\n');

	String alert = (String) session.getAttribute("alert");
	String pwChange = (String) session.getAttribute("pwChange");
	String nickChange = (String) session.getAttribute("nickChange");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar msg = \"");
      out.print(alert);
      out.write("\";\r\n");
      out.write("\tif (msg != \"null\") {\r\n");
      out.write("\t\talert(msg);// 세션에 담긴 메세지 한번만 출력하고 삭제하기\r\n");
	session.removeAttribute("alert");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar pwChange = \"");
      out.print(pwChange);
      out.write("\"\r\n");
      out.write("\tif(pwChange != \"null\"){\r\n");
      out.write("\t\talert(pwChange);\r\n");
	session.removeAttribute("pwChange");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar nickChange = \"");
      out.print(nickChange);
      out.write("\"\r\n");
      out.write("\t\tif(nickChange != \"null\"){\r\n");
      out.write("\t\t\talert(nickChange);\r\n");
      out.write("\t");
	session.removeAttribute("nickChange");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg fixed-top scrolling-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"theme-header clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#main-navbar\" aria-controls=\"main-navbar\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"navbar-brand\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"resources/images/logo12.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 35px;\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t<a style=\"color:black;\">현재접속자수: <span id=userCounting>1</span>명</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \tvar webSocket = new WebSocket('ws://");
      out.print(request.getServerName());
      out.write(':');
      out.print(request.getServerPort());
      out.write("/itjobs/userCounting');\r\n");
      out.write("\twebSocket.onerror = function(event) {\r\n");
      out.write("\t\tonError(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onopen = function(event) {\r\n");
      out.write("\t\tonOpen(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onmessage = function(event) {\r\n");
      out.write("\t\tonMessage(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onclose = function(event) {\r\n");
      out.write("\t\tonClose(event)\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onMessage(event) {//다른사람 동작->나한테 발생\r\n");
      out.write("\t\tcallback(event.data)\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onOpen(event) {\r\n");
      out.write("\t\twebSocket.send(\"어차피 안나올 값\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onError(event) {\r\n");
      out.write("\t\talert(event.data);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onClose(event) {\r\n");
      out.write("\t\twebSocket.send(\"어차피 안나올 값\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction callback(str){\r\n");
      out.write("\t\tvar arr=str.split(',');\r\n");
      out.write("\t\t$('#userCounting').text(arr[0]);\r\n");
      out.write("\t\t$('#todayCount').text(arr[2]);\r\n");
      out.write("\t\t$('#totalCount').text(arr[1]);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"main-navbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto w-100 justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\">\r\n");
      out.write("\t\t\t\t\t\t오늘 <span id=\"todayCount\">&nbsp;</span> · 전체 <span id=\"totalCount\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 안녕하세요.</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"aaa nav-item\">\r\n");
      out.write("\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tHome </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<div></div><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=main\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 게시판 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=main\">전체</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=free\">자유</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=study\">스터디</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=project\">프로젝트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=qu\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=form\">서식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/notificationList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t공고검색 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/resumeList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t인재검색 </a></li>\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null && mem.getType().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\">내 정보수정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myApplyList.vo\">지원리스트\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myNotificationList.like\">관심공고\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/list.re\">이력서관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"mylist.qu\">나의문의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t");
	}else if(mem!=null && mem.getType().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\">내 정보수정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myNotification.me\">공고리스트\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myResumeList.like\">관심인재\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/mylist.qu\">나의문의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
}else if(mem !=null && mem.getType().equals("0")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"button-group\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/memberList.ad\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"button btn btn-common\">관리자</a></li>\r\n");
      out.write("\t\t\t\t\t");
	}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.me\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t");
	}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.me\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/joinlaw.jo\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mobile-menu\" data-logo=\"assets/img/logo-mobile.png\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("   <!-- page-header -->\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"inner-header\">\r\n");
      out.write("\t\t\t\t\t<h3></h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("      var page_header_title='게시판'\r\n");
      out.write("   </script>\r\n");
      out.write("   <!-- end of page-header -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <div id=\"content\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("   <div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("   <div class=\"right-sideabr\">\r\n");
      out.write("   <h4>게시판</h4>\r\n");
      out.write("   <ul class=\"list-item\">\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=main\">전체보기</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=free\">자유</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=study\">스터디</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=project\">프로젝트</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=qu\">공지사항</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.print(contextPath);
      out.write("/listForm.bo?head=form\">서식</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"col-lg-8 col-md-12 col-xs-12\">\r\n");
      out.write("\r\n");
      out.write("   <!--  <section class=\"job-detail section\"> -->\r\n");
      out.write("      <div class=\"job-alerts-item\">\r\n");
      out.write("        <div class=\"row justify-content-between\">\r\n");
      out.write("          <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("           ");
if(mem != null && mem.getM_no() == b.getM_no()) { 
      out.write("\r\n");
      out.write("          <span class=\"btn btn-common float-right\" onclick=\"deleteBtn()\" style=\"margin-left: 10px;\">삭제</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("          <span class=\"btn btn-common float-right\" onclick=\"location.href='");
      out.print(contextPath );
      out.write("/updateForm.bo?bId=");
      out.print(b.getB_no());
      out.write("';\" >수정</span>&nbsp;&nbsp;\r\n");
      out.write("          ");
}else{ 
      out.write("\r\n");
      out.write("           <span class=\"btn btn-common float-right\" id=\"deBtn\">신고</span>\r\n");
      out.write("             ");
}
      out.write("\r\n");
      out.write("            <div class=\"content-area\" style=\"border-bottom:1px solid lightgray\">  \r\n");
      out.write("       \r\n");
      out.write("              <span style=\"font-size:20px;\"> &nbsp;");
      out.print(b.getHead() );
      out.write("</span><br><br>\r\n");
      out.write("              \r\n");
      out.write("              <p style=\"font-size:30px; color:black; font-weight:border;\">");
      out.print(b.getTitle() );
      out.write("</p><br>\r\n");
      out.write("              <span style=\"font-size:18px; color:black;\"> &nbsp;");
      out.print(b.getNickname() );
      out.write("</span>  &nbsp; &nbsp;\r\n");
      out.write("              <span style=\"font-size:18px; color:black;\">");
      out.print(b.getUpdate_date() );
      out.write("</span>&nbsp; &nbsp;&nbsp; &nbsp;\r\n");
      out.write("              <span id=\"img1\">조회수</span>\r\n");
      out.write("              <span style=\"font-size:18px; color:black;\" id=\"img1_1\">");
      out.print(b.getCount() );
      out.write("</span>&nbsp; &nbsp;\r\n");
      out.write("              <span id=\"img2\">댓글수</span>\r\n");
      out.write("           <span style=\"font-size:18px; color:black;\" id=\"img2_1\">");
      out.print(b.getReply_count() );
      out.write("</span> &nbsp; &nbsp;\r\n");
      out.write("            ");
if(b.getEditFile() != null){ 
      out.write("\r\n");
      out.write("           <span id=\"img2\">다운로드수</span>\r\n");
      out.write("           <span style=\"font-size:18px; color:black;\" id=\"img2_1\">");
      out.print( b.getDown_count() );
      out.write("</span>\r\n");
      out.write("           ");
} 
      out.write("\r\n");
      out.write("           </div>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           <br><br>\r\n");
      out.write("           <div style=\"border-bottom:1px solid lightgray\">\r\n");
      out.write("             <pre style=\"font-size:20px;color:black;\">");
      out.print(b.getContents() );
      out.write("</pre><br><br>\r\n");
      out.write("\r\n");
      out.write("            ");
if(b.getVideo() != null){
      out.write("\r\n");
      out.write("            \t<iframe width=\"640\" height=\"360\" src=\"https://www.youtube.com/embed/");
      out.print(videoName[1] );
      out.write("\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("            ");
if(b.getEditFile() != null){ 
      out.write("\r\n");
      out.write("            \t");
if(b.getFile().contains("jpg") || b.getFile().contains("jpeg") || b.getFile().contains("png")){ 
      out.write("\r\n");
      out.write("               \t\t<img class='max-small' id=\"img\" src=\"");
      out.print( contextPath );
      out.write("/resources/fileupload_board/");
      out.print( b.getEditFile());
      out.write("\">\r\n");
      out.write("            \t");
}
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <span>");
      out.print(b.getFile() );
      out.write(" </span>&nbsp; &nbsp;\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/download.bo?bId=");
      out.print(b.getB_no());
      out.write("\" class=\"btn btn-common\">다운로드</a> <br><br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("             ");
 if((b.getHead().equals("스터디") || b.getHead().equals("study"))|| (b.getHead().equals("프로젝트") || b.getHead().equals("project"))){ 
      out.write("\r\n");
      out.write("            <div style=\"font-size:15px;color:black;\">모집기간 - ");
      out.print(b.getTime() );
      out.write("</div><br>\r\n");
      out.write("         \t");
} 
      out.write("              \r\n");
      out.write("           \r\n");
      out.write("         ");
if(prev.getTitle() != null){ 
      out.write("\r\n");
      out.write("             <div id=\"prev\">이전글 - ");
      out.print(prev.getTitle() );
      out.write(" </div>\r\n");
      out.write("          ");
}else { 
      out.write("\r\n");
      out.write("             <div>이전글 - 이전 글이 없습니다.</div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          ");
if(next.getTitle() != null){ 
      out.write("\r\n");
      out.write("             <div id=\"next\">다음글 - ");
      out.print(next.getTitle() );
      out.write(" </div>\r\n");
      out.write("          ");
}else { 
      out.write("\r\n");
      out.write("             <div>다음글 - 다음 글이 없습니다.</div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   <!--  </section> -->\r\n");
      out.write("   \r\n");
      out.write("   <br>\r\n");
      out.write("   <div class=\"job-alerts-item\">\r\n");
      out.write("      <div id=\"replyWrite\" style=\"height:50px;\">\r\n");
      out.write("         <span><textarea rows=\"2\" cols=\"60\" id=\"replyContent\" style=\"resize: none; overflow:auto;\"></textarea></span>\r\n");
      out.write("         <span><a class=\"btn btn-common\" id=\"addReply\"style=\"margin-bottom: 40px;\">등록</a></span>            \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("            <div id=\"replySelect\">\r\n");
      out.write("               \r\n");
      out.write("            \r\n");
      out.write("           </div>\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("      <script>\r\n");
      out.write("   \t\t $(function(){\r\n");
      out.write("   \t\t\t$(\"#prev\").mouseenter(function(){\r\n");
      out.write("   \t\t\t\t$(this).css({\"cursor\":\"pointer\", \"color\":\"red\"});\r\n");
      out.write("   \t\t\t}).mouseleave(function(){\r\n");
      out.write("   \t\t\t\t$(this).css({\"color\":\"gray\"});\r\n");
      out.write("   \t\t\t});\r\n");
      out.write("   \t\t\t$(\"#prev\").click(function(){\r\n");
      out.write("   \t\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/detail.bo?head=");
      out.print(head);
      out.write("&bId=");
      out.print(prev.getB_no() );
      out.write("\";\r\n");
      out.write("   \t\t\t});\r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t$(function(){\r\n");
      out.write("   \t\t\t$(\"#next\").mouseenter(function(){\r\n");
      out.write("   \t\t\t\t$(this).css({\"cursor\":\"pointer\", \"color\":\"red\"});\r\n");
      out.write("   \t\t\t}).mouseleave(function(){\r\n");
      out.write("   \t\t\t\t$(this).css({\"color\":\"gray\"});\r\n");
      out.write("   \t\t\t});\r\n");
      out.write("   \t\t\t\r\n");
      out.write("   \t\t\t$(\"#next\").click(function(){\r\n");
      out.write("   \t\t\t\tlocation.href=\"");
      out.print( contextPath );
      out.write("/detail.bo?head=");
      out.print(head);
      out.write("&bId=");
      out.print(next.getB_no() );
      out.write("\";\r\n");
      out.write("   \t\t\t});\r\n");
      out.write("   \t\t}); \r\n");
      out.write("      \r\n");
      out.write("      $(function(){\r\n");
      out.write("         $(\"#deBtn\").click(function(){\r\n");
      out.write("        \t \r\n");
      out.write("            ");
if(mem!=null && !mem.getType().equals("0")){ 
      out.write("\r\n");
      out.write("           \t\twindow.open(\"");
      out.print(contextPath );
      out.write("/insertForm.de?bId=");
      out.print(b.getB_no());
      out.write("&title=");
      out.print(b.getTitle());
      out.write("&boardNick=");
      out.print(b.getNickname());
      out.write("&head=");
      out.print(b.getHead());
      out.write("\", \"ITJOBS_게시글 신고\", \"width=500, height=600, toolbar=no, menubar=no, scrollbars=no, resizable=no\"); \r\n");
      out.write("            ");
} else if(mem != null && mem.getType().equals("0")){
      out.write("\r\n");
      out.write("            \talert(\"관리자는 신고 불가!\");\r\n");
      out.write("            ");
} else{
      out.write("\r\n");
      out.write("            \talert(\"로그인해주세요\");\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      function deleteBtn(){\r\n");
      out.write("\r\n");
      out.write("         if(confirm(\"정말 삭제하시겠습니까?\") == true){\r\n");
      out.write("            \r\n");
      out.write("            location.href=\"");
      out.print(contextPath);
      out.write("/delete.bo?bId=");
      out.print(b.getB_no());
      out.write("&head=");
      out.print(b.getHead());
      out.write("\";\r\n");
      out.write("         }else{\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      \n");
      out.write("\t\t $(function(){\r\n");
      out.write("\t\t\t\t// 화면 로딩 시 댓글 출력\r\n");
      out.write("\t\t\t\tselectRlist();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsetInterval(function(){\r\n");
      out.write("\t\t\t\t\tselectRlist();\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#addReply\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar reply = $(\"#replyContent\");\r\n");
      out.write("\t\t\t\t\tif(reply.val().trim().length == 0){\r\n");
      out.write("\t\t\t\t\t\talert(\"댓글 내용을 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\treply.focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
if(mem != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\tvar content = $(\"#replyContent\").val();\r\n");
      out.write("\t\t\t\t\tvar bId = ");
      out.print( b.getB_no());
      out.write(";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl:\"brinsert.bo\",\r\n");
      out.write("\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\tdata:{content:content, bId:bId},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(status){\r\n");
      out.write("\t\t\t\t\t\t\tif(status == \"success\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tselectRlist();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#replyContent\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"댓글 작성 실패\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"서버 통신 실패\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\t\talert(\"로그인해야 댓글작성이 가능합니다.\");\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tfunction selectRlist(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"brlist.bo\",\r\n");
      out.write("\t\t\t\tdata:{bId:");
      out.print(b.getB_no() );
      out.write("},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(list){\r\n");
      out.write("\t\t\t\t\tconsole.log(list);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar replySelect = $(\"#replySelect\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treplySelect.html(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(list,function(index, value){\r\n");
      out.write("\t\t\t\t\t\tvar div = $(\"<div>\").css(\"border-bottom\", \"1px dashed lightgray \");\r\n");
      out.write("\t\t\t\t\t\tvar a = $(\"<input type='hidden'>\").text(value.re_no).css(\"width\",\"100px\");\r\n");
      out.write("\t\t\t\t\t\tvar writer = $(\"<span>\").text(value.nickname).css(\"width\",\"100px\");\r\n");
      out.write("\t\t\t\t\t \tvar str1 = $(\"<span>\").text(\" | \");\r\n");
      out.write("\t\t\t\t\t\tvar content = $(\"<div>\").text(value.contents).css(\"width\",\"400px\");\r\n");
      out.write("\t\t\t\t\t\tvar date = $(\"<span>\").text(value.update_date).css(\"width\",\"200px\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    ");
      out.write("\r\n");
      out.write("\t\t                var m_no=0; \r\n");
      out.write("\t\t                ");
if(mem!= null){
      out.write("\r\n");
      out.write("\t\t                m_no=");
      out.print(mem.getM_no());
      out.write(";\r\n");
      out.write("\t\t                ");
}
      out.write("\r\n");
      out.write("\t\t                var deleteRe=$(\"<span>\");\r\n");
      out.write("\t\t                ");
      out.write("\r\n");
      out.write("\t\t                if(m_no==value.m_no){\r\n");
      out.write("\t\t                   deleteRe= $(\"<span>\").text(\"삭제\");\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t\t\t\t \t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdiv.append(a);\r\n");
      out.write("\t\t\t\t\t\tdiv.append(writer);\r\n");
      out.write("\t\t\t\t\t \tdiv.append(str1);\r\n");
      out.write("\t\t\t\t\t\tdiv.append(date);\r\n");
      out.write("\t\t\t\t\t\tdiv.append(content);\r\n");
      out.write("\t\t\t\t\t\tdiv.append(deleteRe);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treplySelect.append(div);\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdeleteRe.click(function(){\r\n");
      out.write("\t\t\t\t\t\t\tvar re_no = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t        url: \"brDelete.bo\",\r\n");
      out.write("\t\t\t\t\t\t        type:\"post\",\r\n");
      out.write("\t\t\t\t\t\t        data: {re_no : re_no},\r\n");
      out.write("\t\t\t\t\t\t        success: function(result){\r\n");
      out.write("\t\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t            if (result==\"success\") {\r\n");
      out.write("\t\t\t\t\t\t                $(\"#div\").remove();\r\n");
      out.write("\t\t\t\t\t\t                alert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t            } else{\r\n");
      out.write("\t\t\t\t\t\t                alert(\"삭제에실패하였습니다\");\r\n");
      out.write("\t\t\t\t\t\t            }\r\n");
      out.write("\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t    })\n");
      out.write("\r\n");
      out.write("                     console.log(re_no);      \r\n");
      out.write("                     console.log($(this).parent().children().eq(0).text());\r\n");
      out.write("                     \r\n");
      out.write("                  })\r\n");
      out.write("                  \r\n");
      out.write("               });\r\n");
      out.write("               \r\n");
      out.write("            },error:function(){\r\n");
      out.write("               console.log(\"서버와의 통신실패!!\");\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <!-- footer -->\r\n");
      out.write("      ");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer-Content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/img/logo-footer.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"block-title\">IT JOBS</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textwidget\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis quis in\r\n");
      out.write("\t\t\t\t\t\t\t\tnulla. Pellentesque volutpat odio eget diam cursus semper.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"block-title\">CHANG JJOCK</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Support</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>License</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Terms & Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Refferal Terms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Product License</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"block-title\">Subscribe Now</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis.</p>\r\n");
      out.write("<!-- \t\t\t\t\t\t<form method=\"post\" id=\"subscribe-form\" name=\"subscribe-form\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"validate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group is-empty\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" value=\"\" name=\"Email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"EMAIL\" placeholder=\"Enter Email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"subscribe\" id=\"subscribes\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-common sub-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"lni-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"mt-3 footer-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"facebook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-facebook-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-twitter-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"linkedin\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-linkedin-fill\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"google-plus\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"copyright\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"site-info text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tBy itjobs chang jjock.\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("   <!-- End of footer -->\r\n");
      out.write("   \r\n");
      out.write("   <!-- back to top button -->\r\n");
      out.write("      <a href=\"#\" class=\"back-to-top\"> <i class=\"lni-arrow-up\"></i></a>\r\n");
      out.write("   <!-- End of back to top button -->\r\n");
      out.write("   \r\n");
      out.write("   <!-- 뭔지 모르겠어 -->\r\n");
      out.write("   <div id=\"preloader\">\r\n");
      out.write("      <div class=\"loader\" id=\"loader-1\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 뭔지 모르겠어 -->\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   $('.inner-header').children('h3').text(page_header_title);\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
