/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-06 12:53:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage.resume;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class resumeWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/include/header.jsp", Long.valueOf(1570015614601L));
    _jspx_dependants.put("/views/include/footer.jsp", Long.valueOf(1569726248500L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	//String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<title>이력서 작성하기</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#header{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:250px;\t\r\n");
      out.write("\tbackground-color:lightgray;\r\n");
      out.write("\t}\r\n");
      out.write("\t#first{\r\n");
      out.write("\tmargin-left:100px;\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#collegeInfo{\r\n");
      out.write("\t\r\n");
      out.write("\t/* display:none; */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#collegeInfo,#highInfo,#academyInfo{\r\n");
      out.write("\t\tpadding:20px;\r\n");
      out.write("\t\tborder:1px solid black;\r\n");
      out.write("\t\twidth:600px;\r\n");
      out.write("\t\tbackground-color:lightgray;\r\n");
      out.write("\t}\r\n");
      out.write("\t#academyInfo{\r\n");
      out.write("\t/* display:none; */\r\n");
      out.write("\t}\r\n");
      out.write("\t#academy,#career{\r\n");
      out.write("\tmargin-left:100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#careerList,#careerList2,#cerList,,#resum_title{\r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#careerList2,#cerList2{\r\n");
      out.write("\tdisplay:none;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#careerList2{\r\n");
      out.write("\tmargin-bottom:100px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"head\"></div>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath=request.getContextPath();
	Member mem=(Member)session.getAttribute("mem");
	String head=request.getParameter("head");
	if(head!=null){
		session.setAttribute("head", head);
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    div.aaa{\r\n");
      out.write("        width:100px;\r\n");
      out.write("        height:30px;\r\n");
      out.write("        border:0px solid;\r\n");
      out.write("        position:relative;\r\n");
      out.write("        float:left;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("    div.aaa div{\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        bottom:0px;\r\n");
      out.write("        width:0%;\r\n");
      out.write("        height:10%;\r\n");
      out.write("        opacity:0.7;\r\n");
      out.write("        background:white;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\r');
      out.write('\n');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<h1><a href=\"");
      out.print(contextPath );
      out.write("\">ITJobs</a></h1>\r\n");
      out.write("<hr>공통 \r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=main\">게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=free\">자유게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=study\">스터디</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=project\">프로젝트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=qna\">공지사항</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=form\">서식</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.qu\"><del>문의사항</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/notificationList.se\">공고검색(기업상세정보)</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/resumeList.se\">인재검색</a>\r\n");
      out.write("<hr>공통\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/views/login/join_law.jsp\">회원가입</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/login.me\">로그인</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a><br>\r\n");
      out.write("<hr>일반\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myApplyList.vo\">지원리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myCompanyList.like\"><del>관심기업</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotificationList.like\"><del>관심공고</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.re\">이력서 관리</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("+지원하기\r\n");
      out.write("<hr>기업\r\n");
      out.write("\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotification.me\">공고리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myResumeList.like\"><del>관심인재</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("<hr>관리자\n");
      out.write("\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/boardList.ad'\">게시판 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/replyList.ad'\">댓글 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/memberList.ad'\">회원 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/noticeList.ad'\">공고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.qu.ad'\">문의 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.de'\">신고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<br clear=\"both\">\r\n");
      out.write("<script>\r\n");
      out.write("    function lease(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("        aaa.eq(n).css({'background':'#ff4e0b','color':'white'})\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, 2000, 'linear', function(){\r\n");
      out.write("            aaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var aaa=$('.aaa')\r\n");
      out.write("\r\n");
      out.write("    aaa.on('mouseover',function(){\r\n");
      out.write("        aaa_div.eq(n).stop()\r\n");
      out.write("    }).on('mouseleave',function(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, (2000*(100-parseFloat(bar.css('width')))/100), 'linear', function(){\r\n");
      out.write("        \taaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    var n=0;\r\n");
      out.write("    var W=$('.aaa').css('width');\r\n");
      out.write("    var aaa_div=$('.aaa').children('div');\r\n");
      out.write("\r\n");
      out.write("    lease()\r\n");
      out.write("</script>\r\n");
      out.write("<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(contextPath);
      out.write("/addResum.re\" method=\"post\">\r\n");
      out.write("<h2 align=\"center\">이력서 작성</h2>\r\n");
      out.write("<div id=\"first\">\r\n");
      out.write("\t\r\n");
      out.write("\t<label name=\"name\">* 이름 : </label>\r\n");
      out.write("\t<input type=\"text\" id=\"name\" name=\"name\" value=\"1\"> <br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<label name=\"birth\">* 생년월일 : </label>\r\n");
      out.write("\t<input type=\"date\" id=\"birth\" name=\"birth\" value=\"2010-01-01\">\r\n");
      out.write("\t\r\n");
      out.write("\t<label name=\"phone\">* 핸드폰번호 : </label>\r\n");
      out.write("\t<input type=\"text\" id=\"phone\" name=\"phone\" value=\"1\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<label name=\"address\">* 주소: </label>\r\n");
      out.write("\t<input type=\"text\" id=\"address\" name=\"address\" value=\"1\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<label name=\"email\">* 이메일: </label>\r\n");
      out.write("\t<input type=\"text\" id=\"email\" name=\"email\" value=\"1\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</div><br><br>\r\n");
      out.write("<div id=\"academy\">\r\n");
      out.write("\t<h3>최종 학력</h3>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"highInfo\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"school_final\" value=\"1\"> 고등학교 졸업<br>\r\n");
      out.write("\t\t<label>학교명</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"school\" value=\"1\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<label>학과명</label>\r\n");
      out.write("\t\t<select name=\"Department\">\r\n");
      out.write("\t\t\t<option value=\"\">--학교계열--</option>\r\n");
      out.write("\t\t\t<option value=\"문과\" selected>문과계열</option>\r\n");
      out.write("\t\t\t<option value=\"이과\">이과계열</option>\r\n");
      out.write("\t\t\t<option value=\"전문\">전문(실업)계</option>\r\n");
      out.write("\t\t\t<option value=\"예체능\">예체능계</option>\r\n");
      out.write("\t\t\t<option value=\"특성화/마이스터\">특성화/마이스터고</option>\r\n");
      out.write("\t\t\t<option value=\"특수목적\">특수목적고</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date1\" value=\"2010-01-01\"> ~\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date2\" value=\"2010-01-01\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"collegeInfo\">\r\n");
      out.write("\t\t<input type=\"radio\" id=\"college\" name=\"school_final\" value=\"2\" checked>초대졸 졸업<br>\r\n");
      out.write("\t\t<label>학교명 </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"school\" value=\"1\"><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>학과명 </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"Department\" value=\"1\"><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date1\" value=\"2010-01-01\"> ~\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date2\" value=\"2010-01-01\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"academyInfo\">\r\n");
      out.write("\t\t<input type=\"radio\" id=\"university\" name=\"school_final\" value=\"3\">대졸 졸업 이상<br>\r\n");
      out.write("\t\t<label>학교</label>\r\n");
      out.write("\t\t<select >\r\n");
      out.write("\t\t\t<option>--대학교--</option>\r\n");
      out.write("\t\t\t<option>대학교 4년제</option>\r\n");
      out.write("\t\t\t<option>대학원(석사)</option>\r\n");
      out.write("\t\t\t<option>대학원(박사)</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label>학교명</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"school\" value=\"1\"><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>학과명</label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"Department\" value=\"1\"><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label>재학기간 </label>\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date1\" value=\"2010-01-01\"> ~\r\n");
      out.write("\t\t<input type=\"date\" name=\"school_Date2\" value=\"2010-01-01\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"career\">\r\n");
      out.write("\t<h3>경력 사항</h3>\r\n");
      out.write("\t<input type=\"radio\" name=\"career\" value=\"N\" checked>신입\r\n");
      out.write("\t<input type=\"radio\" name=\"career\" value=\"Y\" >경력\r\n");
      out.write("\t<input type=\"button\" onclick=\"add_career()\" value=\"+ 경력추가하기\">\r\n");
      out.write("\t<div id=\"careerList\">\r\n");
      out.write("\t\t<div id=\"careerForm\">\r\n");
      out.write("\t\t\t<label>근무 회사명</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"companyName\" value=\"1\"><br><br>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t<label>업무 내용 </label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"workList\" value=\"1\"><br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label>근무 일자</label>\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"workDate1\" value=\"2010-01-01\"> ~\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"workDate2\" value=\"2010-01-01\">\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t<div id=\"careerList2\">\r\n");
      out.write("\t<br>---------------------------------------------------------------------------<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<label>근무 회사명</label>\r\n");
      out.write("\t<input type=\"text\" id=\"companyName\" name=\"companyName\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<label>업무 내용 </label>\r\n");
      out.write("\t<input type=\"text\" id=\"workList\" name=\"workList\"><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<label>근무 일자</label>\r\n");
      out.write("\t<input type=\"date\" id=\"workDate1\" name=\"workDate1\"> ~\r\n");
      out.write("\t<input type=\"date\" id=\"workDate2\" name=\"workDate2\">\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"button\" value=\"삭제하기\" id=\"careerDelete\" name=\"careerDelete\" onclick=\"remove_div(this)\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"cer\">\r\n");
      out.write("\t<h3>자격증</h3>\r\n");
      out.write("\t<input type=\"button\" value=\"+ 자격증 추가하기\" onclick=\"add_cer()\">\r\n");
      out.write("\t<div id=\"cerList\">\r\n");
      out.write("\t\t<div id=\"cerForm\">\r\n");
      out.write("\t\t\t<label>자격증명</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"cer_name\" value=\"1\"><br><br>\r\n");
      out.write("\t\t\t<label>취득날짜</label>\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"cer_date\"  value=\"2010-01-01\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- <div id=\"cerList2\">\r\n");
      out.write("\t<br>---------------------------------------------------------------------------<br><br>\r\n");
      out.write("\t<label>자격증명</label>\r\n");
      out.write("\t<input type=\"text\" id=\"cer_id\" name=\"cer_name\"><br><br>\r\n");
      out.write("\t<label>취득날짜</label>\r\n");
      out.write("\t<input type=\"date\" id=\"cer_date\" name=\"cer_date\"><br>\r\n");
      out.write("\t<input type=\"button\" value=\"삭제하기\" id=\"cerDelete\" name=\"cerDelete\" onclick=\"remove_cer(this)\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"salary\">\r\n");
      out.write("\t<h3>희망연봉</h3><br>\r\n");
      out.write("\t<label>희망연봉금액</label>\r\n");
      out.write("\t<select name=\"hope_salary\">\r\n");
      out.write("\t    <option value=\"회사내규에따름\">회사내규에따름<option>\r\n");
      out.write("\t\t<option value=\"2000만원 ~ 2200만원\">2000만원 ~ 2200만원<option>\r\n");
      out.write("\t\t<option value=\"2200만원 ~ 2400만원\">2200만원 ~ 2400만원<option>\r\n");
      out.write("\t\t<option value=\"2400만원 ~ 2600만원\">2400만원 ~ 2600만원<option>\r\n");
      out.write("\t\t<option value=\"2600만원 ~ 2800만원\">2600만원 ~ 2800만원<option>\r\n");
      out.write("\t\t<option value=\"2800만원 ~ 3000만원\">2800만원 ~ 3000만원<option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"public\">\r\n");
      out.write("\t<h3>이력서 공개 여부</h3>\r\n");
      out.write("\t<label>공개여부</label><br>\r\n");
      out.write("\t<input type=\"radio\" name=\"open\" value=\"Y\" checked>Y\r\n");
      out.write("\t<input type=\"radio\" name=\"open\" value=\"N\" >N\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"resum_title\">\r\n");
      out.write("\t\t<h3>이력서 제목</h3>\r\n");
      out.write("\t\t<label>제목 </label>\r\n");
      out.write("\t\t<input type=\"text\" maxlength=\"100\" size=\"100px\" name=\"title\" value=\"1\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<select name=\"select\" onchange=\"selectInput();\">\r\n");
      out.write("\t\t\t<option value=\"\">== 선택없음 ==</option>\r\n");
      out.write("\t\t\t<option value=\"title_1\" selected>많이 일하고 조금 받겠습니다 뽑아주세요</option>\r\n");
      out.write("\t\t\t<option value=\"title_2\">취업하고 싶습니다 채용해주세요</option>\r\n");
      out.write("\t\t\t<option value=\"title_3\">백수그만하고싶습니다 돈벌게해주세요</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"p_lang\">\r\n");
      out.write("\t\t\t<h3>프로그램언어</h3><br>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"p\" value=\"c언어\" checked>c언어\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"p\" value=\"자바\">자바\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"p\" value=\"CSS\">css\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"p\" value=\"javascript\">javascript\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"self\">\r\n");
      out.write("\t\t<h3>자기소개</h3>\r\n");
      out.write("\t\t<textarea id=\"self\" cols=\"60\" rows=\"10\" name=\"self\">1</textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"submit\" value=\"작성완료\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function setDisplay(){\r\n");
      out.write("    if($('input:radio[id=high]').is(':checked')){\r\n");
      out.write("        $('#highInfo').show();\r\n");
      out.write("        $('#collegeInfo').hide();\r\n");
      out.write("        $('#academyInfo').hide();\r\n");
      out.write("        \r\n");
      out.write("    }else if($('input:radio[id=college]').is(':checked')){ \r\n");
      out.write("    \t$('#highInfo').hide();\r\n");
      out.write("    \t $('#collegeInfo').show();\r\n");
      out.write("        $('#academyInfo').hide();\r\n");
      out.write("    }else{\r\n");
      out.write("    \t$('#highInfo').hide();\r\n");
      out.write("   \t $('#collegeInfo').hide();\r\n");
      out.write("       $('#academyInfo').show();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* function add_div(){\r\n");
      out.write("\r\n");
      out.write("    var div = document.createElement('div');\r\n");
      out.write("\r\n");
      out.write("    div.innerHTML = document.getElementById('careerList2').innerHTML \r\n");
      out.write("\r\n");
      out.write("    document.getElementById('careerList').appendChild(div);\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("function remove_div(obj){\r\n");
      out.write("\r\n");
      out.write("\tdocument.getElementById('careerList').removeChild(obj.parentNode);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function add_cer(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar cer = document.createElement('cer');\r\n");
      out.write("\t\r\n");
      out.write("\tcer.innerHTML = document.getElementById('cerList2').innerHTML\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('cerList').appendChild(cer);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function remove_cer(obj){\r\n");
      out.write("\r\n");
      out.write("\tdocument.getElementById('cerList').removeChild(obj.parentNode);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function selectInput(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar val = $(\"#select option:selected\").html();\r\n");
      out.write("\tconsole.log(val); \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar a =$(\"#title\").val(val);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write("\tfunction add_career(){\r\n");
      out.write("\t/* \t var form=$('#careerForm')\r\n");
      out.write("\t\t var str=form.html();\r\n");
      out.write("\t\t str=str.replace('</div>','<button onclick=\"del_career()\">삭제</button></div>')\r\n");
      out.write("\t\t console.log(str)\r\n");
      out.write("\t\t $('#careerList').append(str) */\r\n");
      out.write("\t \tvar str='<div id=\"careerForm\">';\r\n");
      out.write("\t\tstr+='<label>근무 회사명</label>';\r\n");
      out.write("\t\tstr+='<input type=\"text\" name=\"companyName\" value=\"1\"><br><br>';\r\n");
      out.write("\t\tstr+='<label>업무 내용 </label>';\r\n");
      out.write("\t\tstr+='<input type=\"text\" name=\"workList\" value=\"1\"><br><br>';\r\n");
      out.write("\t\tstr+='<label>근무 일자</label>';\r\n");
      out.write("\t\tstr+='<input type=\"date\" name=\"workDate1\" value=\"2010-01-01\"> ~';\r\n");
      out.write("\t\tstr+='<input type=\"date\" name=\"workDate2\" value=\"2010-01-01\">';\r\n");
      out.write("\t\tstr+='<br><br>';\r\n");
      out.write("\t\tstr+='<span class=\"del_career\" style=\"cursor:pointer;\">삭제</span></div>';\r\n");
      out.write("\t\tstr+='</div>';\r\n");
      out.write("\t\t$('#careerList').append(str)\r\n");
      out.write("\t}\r\n");
      out.write("\t$(document).on('click','.del_career',function(){\r\n");
      out.write("\t\t$(this).closest('div #careerForm').remove();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tfunction add_cer(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar str='<div id=\"cerForm\">';\r\n");
      out.write("\t\tstr+='<label>자격증명</label>';\r\n");
      out.write("\t\tstr+='<input type=\"text\" name=\"cer_name\" value=\"1\"><br><br>';\r\n");
      out.write("\t\tstr+='<label>취득날짜</label>';\r\n");
      out.write("\t\tstr+='<input type=\"date\" name=\"cer_date\"  value=\"2010-01-01\">';\r\n");
      out.write("\t\tstr+='<br>';\r\n");
      out.write("\t\tstr+='<span class=\"del_cer\" style=\"cursor:pointer;\">삭제</span></div>';\r\n");
      out.write("\t\tstr+='</div>';\r\n");
      out.write("\t\t$('#cerList').append(str)\r\n");
      out.write("\t}\r\n");
      out.write("\t$(document).on('click','.del_cer',function(){\r\n");
      out.write("\t\t$(this).closest('div #cerForm').remove();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t<span>Copyright &copy; ITJobs 2019</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
