/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-06 04:47:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.notification.model.vo.Notification;
import java.util.ArrayList;
import com.kh.member.model.vo.Member;

public final class likeNotificationList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/views/include/user/footer.jsp", Long.valueOf(1570290686748L));
    _jspx_dependants.put("/views/include/header.jsp", Long.valueOf(1570015614601L));
    _jspx_dependants.put("/views/include/user/header_nav.jsp", Long.valueOf(1570290686554L));
    _jspx_dependants.put("/views/include/user/page_header.jsp", Long.valueOf(1570290686536L));
    _jspx_dependants.put("/views/include/user/js.jsp", Long.valueOf(1570290686613L));
    _jspx_dependants.put("/views/include/user/style.jsp", Long.valueOf(1570301765407L));
    _jspx_dependants.put("/views/include/user/mypage_menu.jsp", Long.valueOf(1570290686524L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.notification.model.vo.Notification");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- import jobx -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/line-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.theme.default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/slicknav.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/colors/cyan.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/color-switcher.css\">");
      out.write("\r\n");
      out.write("<!-- End of import from jobx -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"home\" class=\"hero-area\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg fixed-top scrolling-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"theme-header clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#main-navbar\" aria-controls=\"main-navbar\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"navbar-brand\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"resources/images/logo1.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 160px; height: 32px;\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"main-navbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto w-100 justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tHome </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 게시판 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=main\">전체</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=free\">자유</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=study\">스터디</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=project\">프로젝트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=qna\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=form\">서식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"pricing.html\">Pricing\r\n");
      out.write("\t\t\t\t\t\t\t\t\tTables</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/notificationList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t공고검색 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/resumeList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t인재검색 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> Candidates </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"browse-jobs.html\">Browse\r\n");
      out.write("\t\t\t\t\t\t\t\t\tJobs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"browse-categories.html\">Browse\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCategories</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"add-resume.html\">Add\r\n");
      out.write("\t\t\t\t\t\t\t\t\tResume</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item active\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"manage-resumes.html\">Manage Resumes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"job-alerts.html\">Job\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAlerts</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> Employers </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"post-job.html\">Add\r\n");
      out.write("\t\t\t\t\t\t\t\t\tJob</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"manage-jobs.html\">Manage\r\n");
      out.write("\t\t\t\t\t\t\t\t\tJobs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"manage-applications.html\">Manage\r\n");
      out.write("\t\t\t\t\t\t\t\t\tApplications</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"browse-resumes.html\">Browse\r\n");
      out.write("\t\t\t\t\t\t\t\t\tResumes</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> Blog </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"blog.html\">Blog -\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRight Sidebar</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"blog-left-sidebar.html\">Blog\r\n");
      out.write("\t\t\t\t\t\t\t\t\t- Left Sidebar</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"blog-full-width.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tBlog full width</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"single-post.html\">Blog\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSingle Post</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.html\">\r\n");
      out.write("\t\t\t\t\t\t\tContact </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">Sign\r\n");
      out.write("\t\t\t\t\t\t\tIn</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"button-group\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/admin/main.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"button btn btn-common\">관리자</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mobile-menu\" data-logo=\"assets/img/logo-mobile.png\"></div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- page-header -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"inner-header\">\r\n");
      out.write("\t\t\t\t\t<h3></h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar page_header_title='내 정보 수정'\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- end of page-header -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- content -->\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- container -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- left -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("\t<div class=\"right-sideabr\">\r\n");
      out.write("\t\t<h4>Manage Account</h4>\r\n");
      out.write("\t\t<ul class=\"list-item\">\r\n");
      out.write("\t\t\t<li><a href=\"resume.html\">이력서 관리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"bookmarked.html\">내가 지원한 기업</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"notifications.html\">Notifications <span\r\n");
      out.write("\t\t\t\t\tclass=\"notinumber\">2</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myCompanyList.like\">관심기업</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myNotificationList.like\">관심공고</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/myResumeList.like\">관심인재</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"job-alerts.html\">비번변경</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/changePw.me\">정보 변경</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"change-password.html\">나의 문의</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"index.html\">탈퇴</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- End of left -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- right  -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-md-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"job-alerts-item bookmarked\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"alerts-title\">좋아요 한 공고</h3>\r\n");
	ArrayList<Notification> list=(ArrayList<Notification>)request.getAttribute("list");
	for(Notification n:list){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"job-listings\" href=\"job-details.html\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-company-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/features/img1.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>");
      out.print(n.getTitle() );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"company-neme\"> ");
      out.print(n.getNickname() );
      out.write(" </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"lni-map-marker\"></i> ");
      out.print(n.getAddress() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-2 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-full-time\">Full Time</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-apply\">Apply Now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-apply\" onclick=\"return del(");
      out.print(n.getNoti_no());
      out.write(");\">삭제</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"job-listings\" href=\"job-details.html\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-company-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/features/img2.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Graphic Designer</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"company-neme\"> Hunter Inc. </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"lni-map-marker\"></i> New Yourk, US\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-2 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-full-time\">Full Time</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-apply\">Apply Now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"job-listings\" href=\"job-details.html\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-company-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/features/img3.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Managing Director</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"company-neme\"> MagNews </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"lni-map-marker\"></i> New Yourk, US\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-2 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-full-time\">Full Time</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-apply\">Apply Now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"job-listings\" href=\"job-details.html\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-4 col-md-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-company-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/features/img4.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"job-details\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3>Software Engineer</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"company-neme\"> AmazeSoft </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"lni-map-marker\"></i> New Yourk, US\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-2 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-full-time\">Full Time</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-12 col-xs-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"btn-apply\">Apply Now</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\" class=\"btn btn-common\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"ti-angle-left\"></i> prev</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\" class=\"btn btn-common\">Next\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ti-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End of right -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End of row -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End of container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End of content -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath=request.getContextPath();
	Member mem=(Member)session.getAttribute("mem");
	String head=request.getParameter("head");
	if(head!=null){
		session.setAttribute("head", head);
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    div.aaa{\r\n");
      out.write("        width:100px;\r\n");
      out.write("        height:30px;\r\n");
      out.write("        border:0px solid;\r\n");
      out.write("        position:relative;\r\n");
      out.write("        float:left;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        cursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("    div.aaa div{\r\n");
      out.write("        position:absolute;\r\n");
      out.write("        bottom:0px;\r\n");
      out.write("        width:0%;\r\n");
      out.write("        height:10%;\r\n");
      out.write("        opacity:0.7;\r\n");
      out.write("        background:white;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\r');
      out.write('\n');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<h1><a href=\"");
      out.print(contextPath );
      out.write("\">ITJobs</a></h1>\r\n");
      out.write("<hr>공통 \r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=main\">게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=free\">자유게시판</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=study\">스터디</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=project\">프로젝트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=qna\">공지사항</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?head=form\">서식</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.qu\"><del>문의사항</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/notificationList.se\">공고검색(기업상세정보)</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/resumeList.se\">인재검색</a>\r\n");
      out.write("<hr>공통\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/views/login/join_law.jsp\">회원가입</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/login.me\">로그인</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a><br>\r\n");
      out.write("<hr>일반\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myApplyList.vo\">지원리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myCompanyList.like\"><del>관심기업</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotificationList.like\"><del>관심공고</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/list.re\">이력서 관리</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("+지원하기\r\n");
      out.write("<hr>기업\r\n");
      out.write("\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myInfo.me\"><del>내 정보 수정</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myNotification.me\">공고리스트</a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/myResumeList.like\"><del>관심인재</del></a>\r\n");
      out.write("<a href=\"");
      out.print(contextPath);
      out.write("/mylist.qu\"><del>나의 문의</del></a>\r\n");
      out.write("<hr>관리자\n");
      out.write("\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/boardList.ad'\">게시판 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/replyList.ad'\">댓글 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/memberList.ad'\">회원 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/noticeList.ad'\">공고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.qu.ad'\">문의 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"aaa\" onclick=\"location.href='");
      out.print(contextPath);
      out.write("/list.de'\">신고 관리\r\n");
      out.write("    <div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<br clear=\"both\">\r\n");
      out.write("<script>\r\n");
      out.write("    function lease(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("        aaa.eq(n).css({'background':'#ff4e0b','color':'white'})\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, 2000, 'linear', function(){\r\n");
      out.write("            aaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var aaa=$('.aaa')\r\n");
      out.write("\r\n");
      out.write("    aaa.on('mouseover',function(){\r\n");
      out.write("        aaa_div.eq(n).stop()\r\n");
      out.write("    }).on('mouseleave',function(){\r\n");
      out.write("        var bar=aaa_div.eq(n)\r\n");
      out.write("\r\n");
      out.write("        $(bar).animate({\r\n");
      out.write("            width: \"100%\",\r\n");
      out.write("        }, (2000*(100-parseFloat(bar.css('width')))/100), 'linear', function(){\r\n");
      out.write("        \taaa.css({'background':'white','color':'black'})\r\n");
      out.write("            aaa_div.css('width','0%')\r\n");
      out.write("            n=(n+1)%6\r\n");
      out.write("            lease()\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("    var n=0;\r\n");
      out.write("    var W=$('.aaa').css('width');\r\n");
      out.write("    var aaa_div=$('.aaa').children('div');\r\n");
      out.write("\r\n");
      out.write("    lease()\r\n");
      out.write("</script>\r\n");
      out.write("<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h1>공고 좋아요</h1>\r\n");
      out.write("<table border=1>\r\n");
      out.write("\t<thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th><input type=checkbox></th>\r\n");
      out.write("\t\t\t<th>공고제목</th>\r\n");
      out.write("\t\t\t<th>기업명</th>\r\n");
      out.write("\t\t\t<th>등록일</th>\r\n");
      out.write("\t\t\t<th>마감일</th>\r\n");
      out.write("\t\t\t<th>상태</th>\r\n");
      out.write("\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\t");
	list=(ArrayList<Notification>)request.getAttribute("list");
			for(Notification n:list){
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><input type=checkbox></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(n.getTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(n.getNickname() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(n.getEnroll_date() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(n.getEnd_date() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(n.getStatus() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td><button onclick=\"del(");
      out.print(n.getNoti_no());
      out.write(',');
      out.print(mem.getM_no());
      out.write(")\">삭제</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
	} 
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction del(noti_no){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/delNotification.like?noti_no=\"+noti_no;\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<button>삭제</button>\r\n");
      out.write("<table border=1>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th><input type=checkbox></th>\r\n");
      out.write("\t\t<th>공고제목</th>\r\n");
      out.write("\t\t<th>기업명</th>\r\n");
      out.write("\t\t<th>등록일</th>\r\n");
      out.write("\t\t<th>마감일</th>\r\n");
      out.write("\t\t<th>삭제</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=checkbox></td>\r\n");
      out.write("\t\t<td><a href=\"get.jsp?bno=1\">제목1</a></td>\r\n");
      out.write("\t\t<td>기업1</td>\r\n");
      out.write("\t\t<td>등록일1</td>\r\n");
      out.write("\t\t<td>수정일1</td>\r\n");
      out.write("\t\t<td><button>삭제</button></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t\t");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer-Content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/img/logo-footer.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textwidget\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis quis in\r\n");
      out.write("\t\t\t\t\t\t\t\tnulla. Pellentesque volutpat odio eget diam cursus semper.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"block-title\">Quick Links</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Support</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">License</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Refferal Terms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Product License</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"block-title\">Subscribe Now</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis.</p>\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" id=\"subscribe-form\" name=\"subscribe-form\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"validate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group is-empty\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" value=\"\" name=\"Email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"EMAIL\" placeholder=\"Enter Email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"subscribe\" id=\"subscribes\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-common sub-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"lni-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"mt-3 footer-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"facebook\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-facebook-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twitter\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-twitter-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"linkedin\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-linkedin-fill\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"google-plus\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"copyright\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"site-info text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tDesigned and Developed by <a href=\"https://uideck.com\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\">UIdeck</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t<!-- End of footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- back to top button -->\r\n");
      out.write("\t\t<a href=\"#\" class=\"back-to-top\"> <i class=\"lni-arrow-up\"></i></a>\r\n");
      out.write("\t<!-- End of back to top button -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 뭔지 모르겠어 -->\r\n");
      out.write("\t<div id=\"preloader\">\r\n");
      out.write("\t\t<div class=\"loader\" id=\"loader-1\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 뭔지 모르겠어 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- import of jobx -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery-min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/color-switcher.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.slicknav.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/form-validator.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/contact-form-script.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/main.js\"></script>");
      out.write("\r\n");
      out.write("\t<!-- End of import of jobx -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$('.inner-header').children('h3').text(page_header_title)\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
