/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-07 11:18:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.board.model.vo.Board;
import com.kh.notification.model.vo.Notification;
import java.util.ArrayList;
import com.kh.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/include/user/footer.jsp", Long.valueOf(1571194974606L));
    _jspx_dependants.put("/views/include/user/header_nav.jsp", Long.valueOf(1573125515900L));
    _jspx_dependants.put("/views/include/user/js.jsp", Long.valueOf(1571194974610L));
    _jspx_dependants.put("/views/include/user/style.jsp", Long.valueOf(1570301765407L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.notification.model.vo.Notification");
    _jspx_imports_classes.add("com.kh.board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/line-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/owl.theme.default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/slicknav.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/colors/cyan.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/jobx/assets/css/color-switcher.css\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery-min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/popper.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"resources/jobx/assets/js/color-switcher.js\"></script> -->\r\n");
      out.write("<script src=\"resources/jobx/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.slicknav.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/form-validator.min.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/contact-form-script.js\"></script>\r\n");
      out.write("<script src=\"resources/jobx/assets/js/main.js\"></script>\r\n");
      out.write("<!-- <script src=\"resources/util/menubar_animation.js\"></script> -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- import jobx -->\r\n");
      out.write("<!-- End of import from jobx -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <header id=\"home\" class=\"hero-area\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath=request.getContextPath();
	Member mem=(Member)session.getAttribute("mem");
	String head=request.getParameter("head");
	/* String googleMem = (String)session.getAttribute("googleMem"); */

	if(head!=null){
		session.setAttribute("head", head);
}

      out.write('\r');
      out.write('\n');

	String alert = (String) session.getAttribute("alert");
	String pwChange = (String) session.getAttribute("pwChange");
	String nickChange = (String) session.getAttribute("nickChange");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar msg = \"");
      out.print(alert);
      out.write("\";\r\n");
      out.write("\tif (msg != \"null\") {\r\n");
      out.write("\t\talert(msg);// 세션에 담긴 메세지 한번만 출력하고 삭제하기\r\n");
	session.removeAttribute("alert");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar pwChange = \"");
      out.print(pwChange);
      out.write("\"\r\n");
      out.write("\tif(pwChange != \"null\"){\r\n");
      out.write("\t\talert(pwChange);\r\n");
	session.removeAttribute("pwChange");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar nickChange = \"");
      out.print(nickChange);
      out.write("\"\r\n");
      out.write("\t\tif(nickChange != \"null\"){\r\n");
      out.write("\t\t\talert(nickChange);\r\n");
      out.write("\t");
	session.removeAttribute("nickChange");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg fixed-top scrolling-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"theme-header clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#main-navbar\" aria-controls=\"main-navbar\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"lni-menu\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"navbar-brand\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"resources/images/logo12.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100px; height: 35px;\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t<a style=\"color:black;\">현재접속자수: <span id=userCounting>1</span>명</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \tvar webSocket = new WebSocket('ws://");
      out.print(request.getServerName());
      out.write(':');
      out.print(request.getServerPort());
      out.write("/itjobs/userCounting');\r\n");
      out.write("\twebSocket.onerror = function(event) {\r\n");
      out.write("\t\tonError(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onopen = function(event) {\r\n");
      out.write("\t\tonOpen(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onmessage = function(event) {\r\n");
      out.write("\t\tonMessage(event)\r\n");
      out.write("\t};\r\n");
      out.write("\twebSocket.onclose = function(event) {\r\n");
      out.write("\t\tonClose(event)\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onMessage(event) {//다른사람 동작->나한테 발생\r\n");
      out.write("\t\tcallback(event.data)\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onOpen(event) {\r\n");
      out.write("\t\twebSocket.send(\"어차피 안나올 값\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onError(event) {\r\n");
      out.write("\t\talert(event.data);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onClose(event) {\r\n");
      out.write("\t\twebSocket.send(\"어차피 안나올 값\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction callback(str){\r\n");
      out.write("\t\tvar arr=str.split(',');\r\n");
      out.write("\t\t$('#userCounting').text(arr[0]);\r\n");
      out.write("\t\t$('#todayCount').text(arr[2]);\r\n");
      out.write("\t\t$('#totalCount').text(arr[1]);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"main-navbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto w-100 justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\">\r\n");
      out.write("\t\t\t\t\t\t오늘 <span id=\"todayCount\">&nbsp;</span> · 전체 <span id=\"totalCount\">&nbsp;</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 안녕하세요.</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"aaa nav-item\">\r\n");
      out.write("\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tHome </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<div></div><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=main\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 게시판 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=main\">전체</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=free\">자유</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=study\">스터디</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=project\">프로젝트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=qu\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.bo?head=form\">서식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/notificationList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t공고검색 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/resumeList.se\">\r\n");
      out.write("\t\t\t\t\t\t\t인재검색 </a></li>\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null && mem.getType().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\">내 정보수정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myApplyList.vo\">지원리스트\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myNotificationList.like\">관심공고\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/list.re\">이력서관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"mylist.qu\">나의문의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t");
	}else if(mem!=null && mem.getType().equals("2")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 마이페이지 </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myInfo.me\">내 정보수정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myNotification.me\">공고리스트\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/myResumeList.like\">관심인재\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/mylist.qu\">나의문의\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
}else if(mem !=null && mem.getType().equals("0")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"button-group\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/memberList.ad\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"button btn btn-common\">관리자</a></li>\r\n");
      out.write("\t\t\t\t\t");
	}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.me\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
	if(mem!=null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t");
	}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.me\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item aaa\"><div></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/joinlaw.jo\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mobile-menu\" data-logo=\"assets/img/logo-mobile.png\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row space-100 justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-10 col-md-12 col-xs-12\">\r\n");
      out.write("               <div class=\"contents\">\r\n");
      out.write("               <h2 class=\"head-title\" >IT JOBS</h2>\r\n");
      out.write("                  <h2 class=\"head-title\">Find the job that fits your life</h2>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"job-search-form\">\r\n");
      out.write("                     <form action=\"notificationList.se\" method=\"get\" autocomplete=off>\r\n");
      out.write("                        <div class=\"row justify-content-md-center\">\r\n");
      out.write("                           <div class=\"col-lg-5 col-md-5 col-xs-12\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input class=\"form-control\" type=\"text\"\r\n");
      out.write("                                    placeholder=\"Job Title or Company Name\" name=\"sText\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <!-- <div class=\"col-lg-3 col-md-6 col-xs-12\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <div class=\"search-category-container\">\r\n");
      out.write("                                    <label class=\"styled-select\"> <select>\r\n");
      out.write("                                          <option value=\"none\">Locations</option>\r\n");
      out.write("                                          <option value=\"none\">New York</option>\r\n");
      out.write("                                          <option value=\"none\">California</option>\r\n");
      out.write("                                          <option value=\"none\">Washington</option>\r\n");
      out.write("                                          <option value=\"none\">Birmingham</option>\r\n");
      out.write("                                          <option value=\"none\">Chicago</option>\r\n");
      out.write("                                          <option value=\"none\">Phoenix</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <i class=\"lni-map-marker\"></i>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-lg-3 col-md-6 col-xs-12\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <div class=\"search-category-container\">\r\n");
      out.write("                                    <label class=\"styled-select\"> <select>\r\n");
      out.write("                                          <option>All Categories</option>\r\n");
      out.write("                                          <option>Finance</option>\r\n");
      out.write("                                          <option>IT & Engineering</option>\r\n");
      out.write("                                          <option>Education/Training</option>\r\n");
      out.write("                                          <option>Art/Design</option>\r\n");
      out.write("                                          <option>Sale/Markting</option>\r\n");
      out.write("                                          <option>Healthcare</option>\r\n");
      out.write("                                          <option>Science</option>\r\n");
      out.write("                                          <option>Food Services</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <i class=\"lni-layers\"></i>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div> -->\r\n");
      out.write("                           <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                              <button type=\"submit\" class=\"button\">\r\n");
      out.write("                                 <i class=\"lni-search\"></i>\r\n");
      out.write("                              </button>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("   <!-- Listings Section Start -->\r\n");
      out.write("   <section id=\"job-listings\" class=\"section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"section-header\">\r\n");
      out.write("            <h2 class=\"section-title\">최신공고</h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("         \r\n");
      out.write("      <!-- 최신공고리스트 -->\r\n");
      out.write("            ");

               ArrayList<Notification> nlist = (ArrayList<Notification>) request.getAttribute("nlist");
               for (Notification n : nlist) {
            
      out.write("\r\n");
      out.write("            <div class=\"col-lg-6 col-md-12 col-xs-12\">\r\n");
      out.write("               <a class=\"job-listings-featured\" href=\"get.no?noti_no=");
      out.print(n.getNoti_no() );
      out.write("\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-lg-8 col-md-6 col-xs-12\">\r\n");
      out.write("                     <div class=\"job-company-logo\">\r\n");
      out.write("                              <img src=\"");
      out.print(contextPath );
      out.write("/resources/cofileupload/");
      out.print(n.getLogoFile() );
      out.write("\" style=\"width:70px;height:70px;\" alt=\"\">\r\n");
      out.write("                        &nbsp;&nbsp;&nbsp;\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"job-details\">\r\n");
      out.write("                           <h3>");
      out.print(n.getTitle());
      out.write("</h3>\r\n");
      out.write("                           <span class=\"company-neme\">");
      out.print(n.getP_language());
      out.write("</span>\r\n");
      out.write("                           <div class=\"tags\">\r\n");
      out.write("                         \r\n");
      out.write("                              <span><i class=\"lni-map-marker\"></i>");
      out.print(n.getNickname());
      out.write("</span>\r\n");
      out.write("                              <span><i class=\"lni-user\"></i>");
      out.print(n.getSalary());
      out.write("만원</span>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"col-lg-4 col-md-6 col-xs-12 text-right\">\r\n");
      out.write("                        <div class=\"tag-type\">\r\n");
      out.write("                           <!--    <sapn class=\"heart-icon\"> <i class=\"lni-heart\"></i> </sapn> -->\r\n");
      out.write("                           <span class=\"full-time\">~");
      out.print(n.getEnd_date().substring(0,10));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

               }
            
      out.write("\r\n");
      out.write("            <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/notificationList.se';\" >더보기</button>\r\n");
      out.write("            <!--  최신공고리스트 끝 -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 마감입박 공고 리스트 -->\r\n");
      out.write("   \r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"section-header\">\r\n");
      out.write("                     <h2 class=\"section-title\">마감 임박 공고</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                     ");

                        ArrayList<Notification> endlist = (ArrayList<Notification>) request.getAttribute("endlist");
                        for (Notification ne : endlist) {
                     
      out.write("\r\n");
      out.write("                     <div class=\"col-lg-6 col-md-12 col-xs-12\">\r\n");
      out.write("                        <a class=\"job-listings-featured\" href=\"get.no?noti_no=");
      out.print(ne.getNoti_no() );
      out.write("\">\r\n");
      out.write("                           <div class=\"row\">\r\n");
      out.write("                              <div class=\"col-lg-8 col-md-6 col-xs-12\">\r\n");
      out.write("                              <div class=\"job-company-logo\">\r\n");
      out.write("                              <img src=\"");
      out.print(contextPath );
      out.write("/resources/cofileupload/");
      out.print(ne.getLogoFile() );
      out.write("\" style=\"width:70px;height:70px;\" alt=\"\">\r\n");
      out.write("                              &nbsp;&nbsp;&nbsp;\r\n");
      out.write("                              </div>\r\n");
      out.write("                                 <div class=\"job-details\">\r\n");
      out.write("                                    <h3>");
      out.print(ne.getTitle() );
      out.write("</h3>\r\n");
      out.write("                                    <span class=\"company-neme\">");
      out.print(ne.getP_language());
      out.write("</span>\r\n");
      out.write("                                    <div class=\"tags\">\r\n");
      out.write("                                       <span><i class=\"lni-map-marker\"></i>");
      out.print(ne.getNickname());
      out.write("</span>\r\n");
      out.write("                                       <span><i class=\"lni-user\"></i>");
      out.print(ne.getSalary());
      out.write("만원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"col-lg-4 col-md-6 col-xs-12 text-right\">\r\n");
      out.write("                                 <div class=\"tag-type\">\r\n");
      out.write("                                    <!--    <sapn class=\"heart-icon\"> <i class=\"lni-heart\"></i> </sapn> -->\r\n");
      out.write("                                    <span class=\"full-time\">~");
      out.print(ne.getEnd_date().substring(0,10));
      out.write("</span>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     ");

                        }
                     
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("   \r\n");
      out.write("                     <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/notificationList.se';\">더보기</button>\r\n");
      out.write("                     <!--  마감임박공고리스트 끝 -->\r\n");
      out.write("\r\n");
      out.write("                  <!-- 공지사항  -->\r\n");
      out.write("                  <br><br><br><br><br><br><br><br>\r\n");
      out.write("               \r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                  <div class=\"section-header\">\r\n");
      out.write("                     <h2 class=\"section-title\">공지사항</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"job-alerts-item candidates\">\r\n");
      out.write("                        \r\n");
      out.write("                           <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>글번호</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\" >\r\n");
      out.write("                                    <p>제목</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>작성자</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>등록날짜</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>조회수</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"alerts-content\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                     ");
   ArrayList<Board> nolist=(ArrayList<Board>)request.getAttribute("nolist");
                           for(Board no:nolist){
      out.write("\r\n");
      out.write("                              <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                              <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(no.getB_no() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\" >\r\n");
      out.write("                                    <a href=\"detail.bo?head=공지사항&bId=");
      out.print(no.getB_no());
      out.write('"');
      out.write('>');
      out.print(no.getTitle() );
      out.write("</a>\r\n");
      out.write("                                 </div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(no.getNickname() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(no.getEnroll_date());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(no.getCount() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              ");
} 
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("   \r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?head=qu';\">더보기</button>\r\n");
      out.write("                        <!-- 공지사항 끝 -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("                  <!-- 자유게시판 -->\r\n");
      out.write("               \r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                  <br><br><br><br><br>\r\n");
      out.write("                  <div class=\"section-header\">\r\n");
      out.write("                     <h2 class=\"section-title\">자유게시판</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"job-alerts-item candidates\">\r\n");
      out.write("                        \r\n");
      out.write("                           <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>글번호</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>제목</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>작성자</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>등록날짜</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>조회수</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"alerts-content\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                      ");
   ArrayList<Board> freelist=(ArrayList<Board>)request.getAttribute("freelist");
                           for(Board s:freelist){
      out.write("\r\n");
      out.write("                              <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                              <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getB_no() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <a href=\"detail.bo?head=자유&bId=");
      out.print(s.getB_no());
      out.write('"');
      out.write('>');
      out.print( s.getTitle());
      out.write("</a>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print( s.getNickname());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getEnroll_date());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getCount() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              ");
} 
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("   \r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?head=free';\" >더보기</button>\r\n");
      out.write("                        <!-- 자유게시판 끝 -->\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- 프로젝트 -->\r\n");
      out.write("               \r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                  <br><br><br><br><br>\r\n");
      out.write("                  <div class=\"section-header\">\r\n");
      out.write("                     <h2 class=\"section-title\">프로젝트</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"job-alerts-item candidates\">\r\n");
      out.write("                        \r\n");
      out.write("                           <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>글번호</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>제목</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>작성자</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>등록날짜</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>조회수</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"alerts-content\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                            ");
   ArrayList<Board> plist=(ArrayList<Board>)request.getAttribute("plist");
                                 for(Board p:plist){
      out.write("\r\n");
      out.write("                              <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                              <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(p.getB_no() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <a href=\"detail.bo?head=프로젝트&bId=");
      out.print(p.getB_no());
      out.write('"');
      out.write('>');
      out.print( p.getTitle());
      out.write("</a>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print( p.getNickname());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(p.getEnroll_date());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(p.getCount() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              ");
} 
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("   \r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?head=project';\" >더보기</button>\r\n");
      out.write("                        <!-- 프로젝트 끝 -->\r\n");
      out.write("                        \r\n");
      out.write("                  <!-- 스터디 -->\r\n");
      out.write("               \r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                  <br><br><br><br><br>\r\n");
      out.write("                  <div class=\"section-header\">\r\n");
      out.write("                     <h2 class=\"section-title\">스터디</h2>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"job-alerts-item candidates\">\r\n");
      out.write("                        \r\n");
      out.write("                           <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>글번호</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>제목</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>작성자</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>등록날짜</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>조회수</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"alerts-content\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                        ");
   ArrayList<Board> slist=(ArrayList<Board>)request.getAttribute("slist");
                              for(Board s:slist){
      out.write("\r\n");
      out.write("                              <div class=\"col-lg-12 col-md-12 col-xs-12\">\r\n");
      out.write("                              <div class=\"alerts-list\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                 <div class=\"col-lg-1 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getB_no() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-5 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <a href=\"detail.bo?head=스터디&bId=");
      out.print(s.getB_no());
      out.write('"');
      out.write('>');
      out.print( s.getTitle());
      out.write("</a>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print( s.getNickname());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getEnroll_date());
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"col-lg-2 col-md-2 col-xs-12\">\r\n");
      out.write("                                    <p>");
      out.print(s.getCount() );
      out.write("</p>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              ");
} 
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("   \r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button class=\"btn btn-common\" style=\"margin-left:89%\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/list.bo?head=study';\" >더보기</button>\r\n");
      out.write("                        <!-- 스터디 끝 -->\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            -\r\n");
      out.write("            <!-- end of how to work -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            ");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"footer-Content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/img/logo-footer.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"block-title\">IT JOBS</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textwidget\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis quis in\r\n");
      out.write("\t\t\t\t\t\t\t\tnulla. Pellentesque volutpat odio eget diam cursus semper.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"block-title\">CHANG JJOCK</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Support</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>License</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Terms & Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Privacy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Refferal Terms</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a>Product License</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"block-title\">Subscribe Now</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>Sed consequat sapien faus quam bibendum convallis.</p>\r\n");
      out.write("<!-- \t\t\t\t\t\t<form method=\"post\" id=\"subscribe-form\" name=\"subscribe-form\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"validate\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group is-empty\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" value=\"\" name=\"Email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"EMAIL\" placeholder=\"Enter Email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"subscribe\" id=\"subscribes\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-common sub-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"lni-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"mt-3 footer-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"facebook\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-facebook-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"twitter\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-twitter-filled\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"linkedin\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-linkedin-fill\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"google-plus\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"lni-google-plus\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"copyright\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"site-info text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tBy itjobs chang jjock.\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("            <!-- End of footer -->\r\n");
      out.write("\r\n");
      out.write("            <!-- back to top button -->\r\n");
      out.write("            <a href=\"#\" class=\"back-to-top\"> <i class=\"lni-arrow-up\"></i></a>\r\n");
      out.write("            <!-- End of back to top button -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 뭔지 모르겠어 -->\r\n");
      out.write("            <div id=\"preloader\">\r\n");
      out.write("               <div class=\"loader\" id=\"loader-1\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 뭔지 모르겠어 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- import of jobx -->\r\n");
      out.write("            <!-- End of import of jobx -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
